import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Adam",
      email: "adamkreiner@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Black Slim Fit Shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 40,
      countInStock: 10,
      brand: "Banana Republic",
      rating: 3.5,
      numReviews: 4,
      description: "high quality product",
    },
    {
      name: "Black T-Shirt",
      category: "Shirts",
      image: "/images/d2.jpg",
      price: 25,
      countInStock: 9,
      brand: "Nike",
      rating: 4,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Bootcut Jeans",
      category: "Pants",
      image: "/images/d3.jpg",
      price: 50,
      countInStock: 20,
      brand: "Levi",
      rating: 4.5,
      numReviews: 9,
      description: "high quality product",
    },
    {
      name: "Black Dress Pants",
      category: "Pants",
      image: "/images/d4.jpg",
      price: 40,
      countInStock: 0,
      brand: "H&M",
      rating: 3,
      numReviews: 14,
      description: "high quality product",
    },
    {
      name: "Grey Sweatpants",
      category: "Pants",
      image: "/images/d5.jpg",
      price: 35,
      countInStock: 15,
      brand: "Nike",
      rating: 4,
      numReviews: 7,
      description: "high quality product",
    },
    {
      name: "Black Sweatpants",
      category: "Pants",
      image: "/images/d6.jpg",
      price: 30,
      countInStock: 7,
      brand: "Athletic Works",
      rating: 3.5,
      numReviews: 6,
      description: "high quality product",
    },
    {
      name: "High Neck Sweater",
      category: "Shirts",
      image: "/images/d7.jpg",
      price: 55,
      countInStock: 7,
      brand: "J.Crew",
      rating: 4.5,
      numReviews: 6,
      description: "high quality product",
    },
  ],
};
export default data;
