const data = {
  products: [
    {
      _id: "1",
      name: "Grey Sweatpants",
      category: "Shirts",
      image: "/images/d5.jpg",
      price: 40,
      countInStock: 10,
      brand: "Nike",
      rating: 1,
      numReviews: 4,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Grey Sweatpants",
      category: "Shirts",
      image: "/images/d5.jpg",
      price: 40,
      countInStock: 9,
      brand: "Nike",
      rating: 1.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Grey Sweatpants",
      category: "Shirts",
      image: "/images/d5.jpg",
      price: 40,
      countInStock: 20,
      brand: "Nike",
      rating: 2.5,
      numReviews: 9,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Grey Sweatpants",
      category: "Shirts",
      image: "/images/d5.jpg",
      price: 40,
      countInStock: 0,
      brand: "Nike",
      rating: 3,
      numReviews: 14,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Grey Sweatpants",
      category: "Shirts",
      image: "/images/d5.jpg",
      price: 40,
      countInStock: 15,
      brand: "Nike",
      rating: 4,
      numReviews: 7,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Grey Sweatpants",
      category: "Shirts",
      image: "/images/d5.jpg",
      price: 30,
      countInStock: 7,
      brand: "Nike",
      rating: 4.5,
      numReviews: 6,
      description: "high quality product",
    },
  ],
};
export default data;
